name: ambar_productivity
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # LIBRERÍAS AÑADIDAS PARA AMBAR:
  # Para grabar voz (Micrófono)
  record: ^5.1.0
  # Para reproducir las notas de voz
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Si en el futuro agregas imágenes o logos, se habilitan aquí:
  # assets:
  #   - assets/images/logo_ambar.png